version: '3.8'

services:
  app:
    build: .
    container_name: cognifog_api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=cognifog_server
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=cognifog_db
      - DB_PORT=5432
    networks:
      - cognifoc_network
    depends_on:
      - cognifog_server
    command: bash -c "npm run migrate && npm start"  # This ensures the migrations run before starting the app
  

  cognifog_server:
    image: postgres:latest
    container_name: cognifog_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cognifog_db
    ports:
      - "5432:5432"
    networks:
      - cognifoc_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  my_pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - cognifoc_network
    depends_on:
      - cognifog_server

networks:
  cognifoc_network:
   driver: bridge


volumes:
  pgdata:
